// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// covidOdeCpp_print_timing
void covidOdeCpp_print_timing();
RcppExport SEXP _comoOdeCpp_covidOdeCpp_print_timing() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    covidOdeCpp_print_timing();
    return R_NilValue;
END_RCPP
}
// covidOdeCpp_reset
void covidOdeCpp_reset();
RcppExport SEXP _comoOdeCpp_covidOdeCpp_reset() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    covidOdeCpp_reset();
    return R_NilValue;
END_RCPP
}
// covidOdeCpp
List covidOdeCpp(double t, const arma::vec& y, const List& parameters, const List& input, int A, const arma::mat& contact_home, const arma::mat& contact_school, const arma::mat& contact_work, const arma::mat& contact_other, const arma::vec& popbirth_col2, const arma::vec& popstruc_col2, const arma::mat& ageing, const arma::vec& ifr_col2, const arma::vec& ihr_col2, const arma::vec& mort_col);
RcppExport SEXP _comoOdeCpp_covidOdeCpp(SEXP tSEXP, SEXP ySEXP, SEXP parametersSEXP, SEXP inputSEXP, SEXP ASEXP, SEXP contact_homeSEXP, SEXP contact_schoolSEXP, SEXP contact_workSEXP, SEXP contact_otherSEXP, SEXP popbirth_col2SEXP, SEXP popstruc_col2SEXP, SEXP ageingSEXP, SEXP ifr_col2SEXP, SEXP ihr_col2SEXP, SEXP mort_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const List& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type contact_home(contact_homeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type contact_school(contact_schoolSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type contact_work(contact_workSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type contact_other(contact_otherSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type popbirth_col2(popbirth_col2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type popstruc_col2(popstruc_col2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ageing(ageingSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ifr_col2(ifr_col2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ihr_col2(ihr_col2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mort_col(mort_colSEXP);
    rcpp_result_gen = Rcpp::wrap(covidOdeCpp(t, y, parameters, input, A, contact_home, contact_school, contact_work, contact_other, popbirth_col2, popstruc_col2, ageing, ifr_col2, ihr_col2, mort_col));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_comoOdeCpp_covidOdeCpp_print_timing", (DL_FUNC) &_comoOdeCpp_covidOdeCpp_print_timing, 0},
    {"_comoOdeCpp_covidOdeCpp_reset", (DL_FUNC) &_comoOdeCpp_covidOdeCpp_reset, 0},
    {"_comoOdeCpp_covidOdeCpp", (DL_FUNC) &_comoOdeCpp_covidOdeCpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_comoOdeCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
